// <auto-generated />
namespace DoAnWebGamingGear.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class InitialCreate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialCreate));
        
        string IMigrationMetadata.Id
        {
<<<<<<<< HEAD:Migrations/202412150120299_InitialCreate.Designer.cs
            get { return "202412150120299_InitialCreate"; }
========
            get { return "202412150110422_InitialCreate"; }
>>>>>>>> a1c937059287ae52724edf6312e882847733c9dc:Migrations/202412150110422_InitialCreate.Designer.cs
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
